config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "messages#index"
  resources :messages, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :content, length: { maximum: 400,
    too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
require 'json'
require 'open-uri'
require 'rest-client'

class MessagesController < ApplicationController
  
  def index
    @messages = Message.all
    @message = Message.new
    @results = covid_data
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    if @message.save
      telegram_crossposting(@message.content)
      redirect_to root_path
    else
      redirect_to root_path
      flash[:notice] =  " Message invalid: #{@message.errors["content"][0]}"
    end 
  end

  def covid_data
    url = 'https://api.covid19api.com/dayone/country/argentina'
    response = open(url).read
    data_array = JSON.parse(response)
    [data_array[-1], data_array.length ]
  end

  def telegram_crossposting(message)
    token = '1703817387:AAFqPLRSdbTH-9aXn1PsKikBlWDebW9q91Q'
    response = RestClient::Request.new(
      :method => :post,
      :url => "https://api.telegram.org/bot#{token}/sendMessage",
      :payload => {"chat_id": "-1001359045591", "text": "#{message}", "disable_notification": true}
    ).execute
    flash[:notice] =  "Message published in Telegram!"
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
    <%= f.input :content, label: false, errors:"Too long", placeholder: "Type your message (max 400 chars)" %>
    <%= f.submit "Publish tweet", class: "btn btn-primary" %>
  <% end %>

app/views/messages/index.html.erb
<div class="container">
  <h2 class="text-center py-5">Covid cases in <%= @results[0]['Country'] %> on the last <%= @results[1] %> days </h2>
</div>
<div class="container my-4 w-50 justify-content-center">
  <div class="row align-items-start individual-cards">
    <div class="col border rounded-top-custom mr-2 d-flex flex-column shadow">
      <p class="card-text text-left mb-0"><strong>Confirmed</strong></p>
      <p> <i class="fas fa-check-circle"></i> <%= number_with_delimiter(@results[0]['Confirmed'], :delimiter => ',') %> cases</p>
    </div>
    <div class="col border rounded-top-custom mr-2 d-flex flex-column shadow">
      <p class="card-text text-left mb-0"><strong>Deaths</strong></p>
      <p> <i class="fas fa-check-circle"></i> <%= number_with_delimiter(@results[0]['Deaths'], :delimiter => ',') %> cases</p>
    </div>
    <div class="col border rounded-top-custom mr-2 d-flex flex-column shadow">
      <p class="card-text text-left mb-0"><strong>Recovered</strong></p>
      <p> <i class="fas fa-check-circle"></i> <%= number_with_delimiter(@results[0]['Recovered'], :delimiter => ',') %> cases</p>
    </div>
    <div class="col border rounded-top-custom mr-2 d-flex flex-column shadow">
      <p class="card-text text-left mb-0"><strong>Active</strong></p>
      <p> <i class="fas fa-check-circle"></i> <%= number_with_delimiter(@results[0]['Active'], :delimiter => ',') %> cases</p>
  </div>
</div>

<div class="container border my-5 shadow">
  <div class="row center p-5">
    <div class="col-xs-12">
      <h2 class="py-4">My messages</h2>
      <div class="container d-flex">
        <%= link_to 'Add Tweet', new_message_path, remote: true, class: "btn btn-primary mr-5"  %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-primary"%>
      </div>
      <% @messages.each do |message| %>
        <div class="message-container pt-4" id="message-<%= message.id %>">
          <i class="author">
            <span>User: <%= message.user.email %></span>
            <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
          </i>
          <p> >> <%= message.content %></p>
        </div>
      <% end %>

    </div>
  </div> 
</div>

<!-- Modal -->
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add your Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/messages/new.js.erb
$('#newModal').modal('show');

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>